/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.util.ArrayList;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author jtx
 */
public class mBusqueda extends javax.swing.JFrame {
    
    private ArrayList<String> columnas;
    private Connection conn;
    private String tableName;
     /*
     * @param conn
     * @param tableName
     * @throws java.sql.SQLException
     */
    public mBusqueda(Connection conn, String tableName) throws SQLException {
        initComponents();
        this.conn = conn;
        this.tableName = tableName;
        //CBOX LLENADO
        ArrayList<String> columnas = getColumns(conn, tableName);
        System.out.println(tableName);
        System.out.println(columnas.toString());
        this.cbox_column.removeAllItems();
        for(int i = 0; i < columnas.size(); i++){
            this.cbox_column.addItem(columnas.get(i));
        };
        llenarTabla(this.conn, this.tableName,this.tf_barraBusqueda.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_filter = new javax.swing.JTable();
        cbox_column = new javax.swing.JComboBox<>();
        tf_barraBusqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_filter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_filter);

        cbox_column.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_column.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_columnActionPerformed(evt);
            }
        });

        tf_barraBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_barraBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_barraBusquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbox_column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_barraBusqueda))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_barraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbox_columnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_columnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_columnActionPerformed

    private void tf_barraBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_barraBusquedaKeyPressed
        //
        
    }//GEN-LAST:event_tf_barraBusquedaKeyPressed

    private void tf_barraBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_barraBusquedaKeyReleased
        try {
            this.llenarTabla(this.conn,this.tableName,this.tf_barraBusqueda.getText());
        } catch (SQLException ex) {
            Logger.getLogger(mBusqueda.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("fue p");
        }
    }//GEN-LAST:event_tf_barraBusquedaKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbox_column;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_filter;
    private javax.swing.JTextField tf_barraBusqueda;
    // End of variables declaration//GEN-END:variables

    private ArrayList<String> getColumns(Connection conn, String tableName) throws SQLException {
        ArrayList<String> columnNames = new ArrayList<>();
        DatabaseMetaData md = conn.getMetaData();
        try (ResultSet rs = md.getColumns(null, null, tableName, null) // Asegúrate de cerrar ResultSet
                ) 
        {    // Obtén las columnas para la tabla especificada
            while (rs.next()) {
                columnNames.add(rs.getString("COLUMN_NAME"));
            }
        } catch (SQLException e) {
            System.out.println("Error");
        }

        return columnNames;
    }
    private ArrayList<Object[]> getInfo(Connection conn, String tableName, String buscador) throws SQLException {
        ArrayList<Object[]> data = new ArrayList<>();
        String query = "SELECT * FROM "+ tableName + " WHERE "+ this.cbox_column.getSelectedItem() + " LIKE ?";
        PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setString(1, "%" + buscador + "%");
        ResultSet rs = stmt.executeQuery();   
        int columnCount = rs.getMetaData().getColumnCount();
            
        while (rs.next()) {
            Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                data.add(row);
            }
        return data;
    }

    private void llenarTabla(Connection conn, String tableName, String buscador) throws SQLException {
        ArrayList<String> columnas = getColumns(conn, tableName);
        ArrayList<Object[]> data = getInfo(conn, tableName,buscador);
        
        // Convert column names to an array
        String[] columns = columnas.toArray(String[]::new);

        // Convert data to a 2D array
        Object[][] tableData = new Object[data.size()][columns.length];
        for (int i = 0; i < data.size(); i++) {
            tableData[i] = data.get(i);
        }
        // Create the table model and table
        DefaultTableModel model = new DefaultTableModel(tableData, columns);
        this.tbl_filter.setModel(model);
    }
    
}
