/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author jtx
 */
public class mSelectorModulos extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public mSelectorModulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        letras17 = new javax.swing.JLabel();
        btn_mHabitaciones1 = new javax.swing.JButton();
        btn_mHabitaciones = new javax.swing.JButton();
        btn_mClientes1 = new javax.swing.JButton();
        btn_mClientes = new javax.swing.JButton();
        btn_mPagos1 = new javax.swing.JButton();
        btn_mPagos = new javax.swing.JButton();
        btn_mEmpleados1 = new javax.swing.JButton();
        btn_mEmpleados = new javax.swing.JButton();
        btn_mReservas1 = new javax.swing.JButton();
        btn_mReservas = new javax.swing.JButton();
        btn_mUsuarios1 = new javax.swing.JButton();
        btn_mUsuarios = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(774, 512));
        setResizable(false);

        letras17.setFont(letras17.getFont().deriveFont(letras17.getFont().getStyle() | java.awt.Font.BOLD, 26));
        letras17.setText("Selector de Modulos");

        btn_mHabitaciones1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mHabitaciones1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mHabitaciones.setFont(btn_mHabitaciones.getFont().deriveFont((btn_mHabitaciones.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mHabitaciones.getFont().getSize()+3));
        btn_mHabitaciones.setText("Habitaciones");
        btn_mHabitaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mClientes1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mClientes1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mClientes.setFont(btn_mClientes.getFont().deriveFont((btn_mClientes.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mClientes.getFont().getSize()+3));
        btn_mClientes.setText("Clientes");
        btn_mClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mPagos1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mPagos1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mPagos.setFont(btn_mPagos.getFont().deriveFont((btn_mPagos.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mPagos.getFont().getSize()+3));
        btn_mPagos.setText("Pagos");
        btn_mPagos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mEmpleados1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mEmpleados1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mEmpleados.setFont(btn_mEmpleados.getFont().deriveFont((btn_mEmpleados.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mEmpleados.getFont().getSize()+3));
        btn_mEmpleados.setText("Empleados");
        btn_mEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mReservas1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mReservas1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mReservas.setFont(btn_mReservas.getFont().deriveFont((btn_mReservas.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mReservas.getFont().getSize()+3));
        btn_mReservas.setText("Reservas");
        btn_mReservas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mUsuarios1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mUsuarios1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_mUsuarios.setFont(btn_mUsuarios.getFont().deriveFont((btn_mUsuarios.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mUsuarios.getFont().getSize()+3));
        btn_mUsuarios.setText("Usuarios");
        btn_mUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        btn_back.setBackground(new java.awt.Color(255, 204, 0));
        btn_back.setText("<<<");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_mReservas1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btn_mReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_mPagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btn_mPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_mHabitaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btn_mHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_mClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btn_mClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_mUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btn_mUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_mEmpleados1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btn_mEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(letras17)))
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(letras17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mHabitaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mPagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mReservas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mEmpleados1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.abrirLogin();
        //ELIMINAR
        super.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_mClientes;
    private javax.swing.JButton btn_mClientes1;
    private javax.swing.JButton btn_mEmpleados;
    private javax.swing.JButton btn_mEmpleados1;
    private javax.swing.JButton btn_mHabitaciones;
    private javax.swing.JButton btn_mHabitaciones1;
    private javax.swing.JButton btn_mPagos;
    private javax.swing.JButton btn_mPagos1;
    private javax.swing.JButton btn_mReservas;
    private javax.swing.JButton btn_mReservas1;
    private javax.swing.JButton btn_mUsuarios;
    private javax.swing.JButton btn_mUsuarios1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel letras17;
    // End of variables declaration//GEN-END:variables
    public void desabilitarModulos() {
        this.btn_mUsuarios.setEnabled(false);
        this.btn_mUsuarios1.setEnabled(false);
        this.btn_mEmpleados.setEnabled(false);
        this.btn_mEmpleados1.setEnabled(false);
    }
    
    public void abrirLogin(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            //UIManager.put( "Button.arc", 999 );
            //UIManager.put( "Component.arc", 999 );
            //UIManager.put( "ProgressBar.arc", 999 );
            //UIManager.put( "TextComponent.arc", 999 );
            UIManager.put("Button.arc", 2); // Radio de las esquinas redondeadas
            UIManager.put("Button.borderColor", Color.BLACK); // Color del borde
            UIManager.put("Button.focusedBorderColor", Color.BLACK); // Color del borde cuando está enfocado
            UIManager.put("Button.default.borderColor", Color.BLACK); // Color del borde para el botón por defecto
            UIManager.put("Component.borderWidth", 2);

            //UIManager.put("Button.border", new LineBorder(Color.BLACK,2));
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
            
        });
    }
}
