/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.awt.*;
import javax.swing.*;
//import gui.SQLConnection.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import sql.dbConnection;

/**
 *
 * @author jtx
 */

public class mUsuariosModificar extends javax.swing.JFrame {

    /**
     * Creates new form mUsuariosModificar
     */
    private Connection conn = null;

    public mUsuariosModificar() {
        initComponents();
        conn = dbConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tf_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chk_admin = new javax.swing.JCheckBox();
        btn_aplicar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        chk_new = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(tf_nombre);
        tf_nombre.setBounds(10, 100, 64, 25);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 52, 19);

        tf_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_idKeyReleased(evt);
            }
        });
        getContentPane().add(tf_id);
        tf_id.setBounds(40, 40, 64, 25);
        getContentPane().add(tf_contra);
        tf_contra.setBounds(100, 100, 64, 25);

        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 80, 73, 19);

        jLabel4.setText("Rol");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 80, 19, 19);

        chk_admin.setText("Admin");
        chk_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_adminActionPerformed(evt);
            }
        });
        getContentPane().add(chk_admin);
        chk_admin.setBounds(190, 100, 63, 23);

        btn_aplicar.setText("Aplicar");
        btn_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aplicar);
        btn_aplicar.setBounds(280, 150, 73, 25);

        jLabel5.setText("ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 40, 15, 19);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Modificar existente");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(140, 10, 160, 23);

        buttonGroup1.add(chk_new);
        chk_new.setText("Crear Usuario");
        chk_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_newActionPerformed(evt);
            }
        });
        getContentPane().add(chk_new);
        chk_new.setBounds(10, 10, 111, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_adminActionPerformed

    private void btn_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aplicarActionPerformed
        boolean modoCrear = this.chk_new.isSelected();
        if (modoCrear) {
            
            añadirUsuario(conn);
        } else {
            modificarUsuario(conn);
        }

    }//GEN-LAST:event_btn_aplicarActionPerformed

    private void tf_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idKeyReleased
        String id = this.tf_id.getText();
        buscarID(conn, id);
    }//GEN-LAST:event_tf_idKeyReleased

    private void chk_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_newActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mUsuariosModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mUsuariosModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mUsuariosModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mUsuariosModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mUsuariosModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aplicar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk_admin;
    private javax.swing.JRadioButton chk_new;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables

    private void buscarID(Connection con, String id) {

        String query = "SELECT nombre_usuario, contrasena, admin FROM Usuarios WHERE usuario_id = ?";

        try (PreparedStatement statement = conn.prepareStatement(query)) {
            statement.setString(1, id);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    String nombre = resultSet.getString("nombre_usuario");
                    String contraseña = resultSet.getString("contrasena");
                    boolean esAdmin = resultSet.getBoolean("admin");
                    this.tf_nombre.setText(nombre);
                    this.tf_contra.setText(contraseña);
                    this.chk_admin.setSelected(esAdmin);
                    this.lbl_encontrado.setText("Usuario existente, aplicar para modificar");
                } else {
                    System.out.println("Usuario no encontrado");
                    this.lbl_encontrado.setText("Usuario no encontrado");
                    this.tf_nombre.setText("---");
                    this.tf_contra.setText("---");
                    this.chk_admin.setSelected(false);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private int ultimoIdDisponible(Connection conn) throws SQLException {
        String ultimoIDQuery = "SELECT MAX(usuario_id) AS ultimo_id FROM Usuarios";
        int nuevoID = 1; // Valor por defecto para el primer usuario
       
        PreparedStatement ultimoIDStmt = conn.prepareStatement(ultimoIDQuery);
        ResultSet rs = ultimoIDStmt.executeQuery();
        if (rs.next()) {
            nuevoID = rs.getInt("ultimo_id") + 1;
        }
        return nuevoID;
    }

    private void añadirUsuario(Connection conn) {

        String insertQuery = "INSERT INTO Usuarios (usuario_id, nombre_usuario, contrasena, admin, creado_en, actualizado_en) VALUES (?, ?, ?, ?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";

        try {
            // Obtener el último ID

            // Obtener los valores para el nuevo usuario
            String nombre = this.tf_nombre.getText();
            String contraseña = this.tf_contra.getText();
            boolean esAdmin = this.chk_admin.isSelected();

            // Insertar el nuevo usuario
            int nuevoID = ultimoIdDisponible(conn);
            
            PreparedStatement insertStmt = conn.prepareStatement(insertQuery);
            insertStmt.setInt(1, nuevoID);
            insertStmt.setString(2, nombre);
            insertStmt.setString(3, contraseña);
            insertStmt.setBoolean(4, esAdmin);

            int filasInsertadas = insertStmt.executeUpdate();
            if (filasInsertadas > 0) {
                JOptionPane.showMessageDialog(rootPane, "Usuario añadido exitosamente");
            }
            this.chk_new.setSelected(false);
            this.chk_admin.setSelected(false);
            this.tf_contra.setText("");
            this.tf_nombre.setText("");
            this.tf_id.setText("");
            insertStmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void modificarUsuario(Connection conn) {
        String query = "";
    }
}
}
