/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

//import configuracion.Conexion;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.lang.System.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.logging.Level;
import javax.swing.JTextField;
import sql.dbConnection;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 *
 * @author USER
 */
public class mClientes extends javax.swing.JFrame {

    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int ID;
    private Connection conn = null;
    
    public boolean modoDialogo = false;

    public mClientes() {
        initComponents();
        setLocationRelativeTo(null);
        conn = dbConnection.connect();
        listar();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mHabitacionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mHabitacionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mHabitacionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mHabitacionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mClientes().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombrestxt = new javax.swing.JTextField();
        apellidostxt = new javax.swing.JTextField();
        direcciontxt = new javax.swing.JTextField();
        correotxt = new javax.swing.JTextField();
        nrotxt = new javax.swing.JTextField();
        nacionalidadtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fondo = new javax.swing.JButton();
        fondo1 = new javax.swing.JButton();
        fondo2 = new javax.swing.JButton();
        fondo4 = new javax.swing.JButton();
        editarbt = new javax.swing.JButton();
        registrartxt = new javax.swing.JButton();
        eliminarbt = new javax.swing.JButton();
        buscarbt = new javax.swing.JButton();
        dnitxt = new javax.swing.JTextField();
        limpiarbt1 = new javax.swing.JButton();
        fondo6 = new javax.swing.JButton();
        btn_mHabitaciones7 = new javax.swing.JButton();
        btn_mHabitaciones8 = new javax.swing.JButton();
        retornar1 = new javax.swing.JButton();
        fondo3 = new javax.swing.JButton();
        btn_idCopia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "DNI", "Correo", "Nro. Celular", "Direccion", "Nacionalidad"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 780, 210));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 88, 30));

        jLabel2.setText("Apellidos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 88, 30));

        jLabel3.setText("Nro. Celular:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 60, 80, 30));

        jLabel4.setText("Correo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 88, 30));

        jLabel5.setText("DNI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 40, 30));

        jLabel6.setText("Direccion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 30));

        jLabel7.setText("Nacionalidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 96, 80, 30));

        nombrestxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        nombrestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrestxtActionPerformed(evt);
            }
        });
        jPanel1.add(nombrestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 150, 30));

        apellidostxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(apellidostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, 30));

        direcciontxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        direcciontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direcciontxtActionPerformed(evt);
            }
        });
        jPanel1.add(direcciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, 30));

        correotxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        correotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correotxtActionPerformed(evt);
            }
        });
        jPanel1.add(correotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 150, 30));

        nrotxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        nrotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrotxtActionPerformed(evt);
            }
        });
        jPanel1.add(nrotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 167, 30));

        nacionalidadtxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        nacionalidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadtxtActionPerformed(evt);
            }
        });
        jPanel1.add(nacionalidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 96, 167, 30));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 167, 101));

        fondo.setBackground(new java.awt.Color(255, 204, 0));
        fondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 20, 20));

        fondo1.setBackground(new java.awt.Color(255, 204, 0));
        fondo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 20, 20));

        fondo2.setBackground(new java.awt.Color(255, 204, 0));
        fondo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 20, 30));

        fondo4.setBackground(new java.awt.Color(255, 204, 0));
        fondo4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 20, 20));

        editarbt.setText("EDITAR   ");
        editarbt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        editarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbtActionPerformed(evt);
            }
        });
        jPanel1.add(editarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 100, 20));

        registrartxt.setText("REGISTRAR   ");
        registrartxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        registrartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrartxtActionPerformed(evt);
            }
        });
        jPanel1.add(registrartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 100, 20));

        eliminarbt.setText("ELIMINAR   ");
        eliminarbt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        eliminarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbtActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 20));

        buscarbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/lupa.png"))); // NOI18N
        buscarbt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buscarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtActionPerformed(evt);
            }
        });
        jPanel1.add(buscarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 40, 30));

        dnitxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        dnitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnitxtActionPerformed(evt);
            }
        });
        jPanel1.add(dnitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 167, 30));

        limpiarbt1.setText("LIMPIAR   ");
        limpiarbt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        limpiarbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbt1ActionPerformed(evt);
            }
        });
        jPanel1.add(limpiarbt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 100, 20));

        fondo6.setBackground(new java.awt.Color(255, 204, 0));
        fondo6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(fondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 20, 20));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 780, 210));

        btn_mHabitaciones7.setBackground(new java.awt.Color(204, 204, 204));
        btn_mHabitaciones7.setBorder(null);
        jPanel2.add(btn_mHabitaciones7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 780, 200));

        btn_mHabitaciones8.setBackground(new java.awt.Color(204, 204, 204));
        btn_mHabitaciones8.setBorder(null);
        jPanel2.add(btn_mHabitaciones8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 780, 210));

        retornar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/devolver.png"))); // NOI18N
        retornar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        retornar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornar1ActionPerformed(evt);
            }
        });
        jPanel2.add(retornar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        fondo3.setBackground(new java.awt.Color(255, 204, 51));
        fondo3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 10, 30));

        btn_idCopia.setText("CopiarID");
        btn_idCopia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_idCopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idCopiaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_idCopia, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 100, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila = tabla.getSelectedRow();
        if (fila == -1) {
        } else {
            String nombres = (String) tabla.getValueAt(fila, 1);
            this.nombrestxt.setText(nombres);
            String apellidos = (String) tabla.getValueAt(fila, 2);
            this.apellidostxt.setText(apellidos);
            String dni = (String) tabla.getValueAt(fila, 3);
            this.dnitxt.setText(dni);
            String correo = (String) tabla.getValueAt(fila, 4);
            this.correotxt.setText(correo);
            String nro = (String) tabla.getValueAt(fila, 5);
            this.nrotxt.setText(nro);
            String direccion = (String) tabla.getValueAt(fila, 6);
            this.direcciontxt.setText(direccion);
            String nacionalidad = (String) tabla.getValueAt(fila, 7);
            this.nacionalidadtxt.setText(nacionalidad);
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseEntered

    private void nacionalidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadtxtActionPerformed

    private void nrotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrotxtActionPerformed

    private void correotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correotxtActionPerformed

    private void direcciontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direcciontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direcciontxtActionPerformed

    private void nombrestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrestxtActionPerformed

    private void editarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbtActionPerformed
        editar();
    }//GEN-LAST:event_editarbtActionPerformed

    private void registrartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrartxtActionPerformed
        registrar();
    }//GEN-LAST:event_registrartxtActionPerformed

    private void btn_idCopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idCopiaActionPerformed
        copiarID();
    }//GEN-LAST:event_btn_idCopiaActionPerformed

    private void eliminarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbtActionPerformed
        eliminar();
    }//GEN-LAST:event_eliminarbtActionPerformed

    private void buscarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtActionPerformed
        buscarCliente();
    }//GEN-LAST:event_buscarbtActionPerformed

    private void retornar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornar1ActionPerformed

        retornarModulo();
    }//GEN-LAST:event_retornar1ActionPerformed

    private void dnitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnitxtActionPerformed

    private void limpiarbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarbt1ActionPerformed

    public void retornarModulo() {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    void editar() {
        String nombres = nombrestxt.getText();
        String apellidos = apellidostxt.getText();
        String nro = nrotxt.getText();
        String correo = correotxt.getText();
        String direccion = direcciontxt.getText();
        String nacionalidad = nacionalidadtxt.getText();
        String dni = dnitxt.getText();
        int fila = tabla.getSelectedRow();
        int id = (int) tabla.getValueAt(fila, 0);
        int DN = Integer.parseInt((String) tabla.getValueAt(fila, 3).toString());
        if (nro.equals("") || nombres.equals("") || apellidos.equals("") || dni.equals("") || correo.equals("") || direccion.equals("") || nacionalidad.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar datos en las cajas.");
        } else {
            int contador_de_errores = 0;
            for (int i = 0; i < tabla.getRowCount(); i++) {
                int DNI = Integer.parseInt((String) tabla.getValueAt(i, 3).toString());
                if (DNI == Integer.parseInt(dni)) {
                    contador_de_errores = 1;
                }
            }
            if (DN == Integer.parseInt(dni)) {
                contador_de_errores = 0;
            }
            String sql = "update Clientes set nombre='" + nombres + "',apellido='" + apellidos + "',dni='" + dni + "',correo_electronico='" + correo + "',telefono='" + nro + "',direccion='" + direccion + "',nacionalidad='" + nacionalidad + "' where cliente_id=" + id;
            if (contador_de_errores == 0) {
                try {
                    cn = dbConnection.connect();
                    st = cn.createStatement();
                    st.executeUpdate(sql);
                    limpiartabla();

                } catch (Exception e) {
                }
                listar();
                nuevo();
            } else {
                JOptionPane.showMessageDialog(null, "Los nombres y apellidos que ingreso ya fue registrada en el sistema.");
            }

        }
    }

    private void buscarCliente() {
        mBusqueda buscar = null;
        try {
            buscar = new mBusqueda(conn, "Clientes");
            buscar.setVisible(true);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(mUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void eliminar() {
        int fila = tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Se requiere seleccionar un cliente");
        } else {
            int id = (int) tabla.getValueAt(fila, 0);
            String sql = "delete from Clientes where cliente_id=" + id;
            try {
                cn = dbConnection.connect();
                st = cn.createStatement();
                st.executeUpdate(sql);
                limpiartabla();
            } catch (SQLException e) {
            }
            listar();
            nuevo();
        }
    }

    void registrar() {
        String nombres = nombrestxt.getText();
        String dni = dnitxt.getText();
        String apellidos = apellidostxt.getText();
        String correo = correotxt.getText();
        String nro = nrotxt.getText();
        String direccion = direcciontxt.getText();
        String nacionalidad = nacionalidadtxt.getText();

        if (nro.equals("") || nombres.equals("") || apellidos.equals("") || dni.equals("") || correo.equals("") || direccion.equals("") || nacionalidad.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar datos en las cajas.");
        } else {
            int contador_de_errores = 0;
            for (int i = 0; i < tabla.getRowCount(); i++) {
                int DNI = Integer.parseInt((String) tabla.getValueAt(i, 3).toString());
                if (DNI == Integer.parseInt(dni)) {
                    contador_de_errores = 1;
                }
            }
            if (contador_de_errores == 0) {
                String sql = "insert into Clientes(nombre,apellido,dni,correo_electronico,telefono,direccion,nacionalidad)values('" + nombres + "','" + apellidos + "','" + dni + "','" + correo + "','" + nro + "','" + direccion + "','" + nacionalidad + "')";
                try {
                    cn = dbConnection.connect();
                    st = cn.createStatement();
                    st.executeUpdate(sql);
                    limpiartabla();
                } catch (Exception e) {
                }
                listar();
                nuevo();
            } else {
                JOptionPane.showMessageDialog(null, "El dni que ingreso ya fue registrado en el sistema.");
            }
        }
    }

    void limpiartabla() {
        for (int i = 0; i <= tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    void nuevo() {
        nombrestxt.setText("");
        nrotxt.setText("");
        correotxt.setText("");
        apellidostxt.setText("");
        nacionalidadtxt.setText("");
        direcciontxt.setText("");
        dnitxt.setText("");
    }

    void listar() {
        String sql = "select * from Clientes";
        try {
            cn = dbConnection.connect();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] clientes = new Object[8];
            modelo = (DefaultTableModel) tabla.getModel();
            while (rs.next()) {
                clientes[0] = rs.getInt("cliente_id");
                clientes[1] = rs.getString("nombre");
                clientes[2] = rs.getString("apellido");
                clientes[3] = rs.getString("dni");
                clientes[4] = rs.getString("correo_electronico");
                clientes[5] = rs.getString("telefono");
                clientes[6] = rs.getString("direccion");
                clientes[7] = rs.getString("nacionalidad");
                modelo.addRow(clientes);
            }
            tabla.setModel(modelo);
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidostxt;
    private javax.swing.JButton btn_idCopia;
    private javax.swing.JButton btn_mHabitaciones7;
    private javax.swing.JButton btn_mHabitaciones8;
    private javax.swing.JButton buscarbt;
    private javax.swing.JTextField correotxt;
    private javax.swing.JTextField direcciontxt;
    private javax.swing.JTextField dnitxt;
    private javax.swing.JButton editarbt;
    private javax.swing.JButton eliminarbt;
    private javax.swing.JButton fondo;
    private javax.swing.JButton fondo1;
    private javax.swing.JButton fondo2;
    private javax.swing.JButton fondo3;
    private javax.swing.JButton fondo4;
    private javax.swing.JButton fondo6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiarbt1;
    private javax.swing.JTextField nacionalidadtxt;
    private javax.swing.JTextField nombrestxt;
    private javax.swing.JTextField nrotxt;
    private javax.swing.JButton registrartxt;
    private javax.swing.JButton retornar1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private void copiarID() {
        int fila = tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una columna!");
        } else {
            String ID = (String) tabla.getValueAt(fila, 0).toString();
            portapapeles(ID);
            JOptionPane.showMessageDialog(rootPane, "ID: " + ID + "\nCopiado al portapapeles");
            this.retornarModulo();
        }

    }

    private void portapapeles(String value) {
        StringSelection stringSelection = new StringSelection(value);

        // Obtener el portapapeles del sistema
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        // Copiar el texto al portapapeles
        clipboard.setContents(stringSelection, null);
    }

}
