/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

//import configuracion.Conexion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.dbConnection;

public class mEmpleados extends javax.swing.JFrame {
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    String ID;
    private Connection conn = null;
    
    
    public mEmpleados() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
        conn = dbConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        editarbtn = new javax.swing.JButton();
        buscarbtn = new javax.swing.JButton();
        nuevobtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        comodidadestxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripciontxt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipocb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        nrotxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pisotxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        estadocb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        preciotxt = new javax.swing.JTextField();
        fond = new javax.swing.JButton();
        fond1 = new javax.swing.JButton();
        fond2 = new javax.swing.JButton();
        btn_mHabitaciones7 = new javax.swing.JButton();
        btn_mHabitaciones8 = new javax.swing.JButton();
        btn_mHabitaciones9 = new javax.swing.JButton();
        btn_mHabitaciones10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 22, -1, 128));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarbtn.setText("EDITAR");
        editarbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        editarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbtnActionPerformed(evt);
            }
        });
        jPanel4.add(editarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 150, 30));

        buscarbtn.setText("BUSCAR");
        buscarbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtnActionPerformed(evt);
            }
        });
        jPanel4.add(buscarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 150, 30));

        nuevobtn.setText("LIMPIAR");
        nuevobtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        nuevobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevobtnActionPerformed(evt);
            }
        });
        jPanel4.add(nuevobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 150, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Comodidades"));

        comodidadestxt.setColumns(20);
        comodidadestxt.setRows(5);
        jScrollPane4.setViewportView(comodidadestxt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nro", "Piso", "Tipo", "Precio", "Estado", "Descrip.", "Comod."
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 425, 335));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion:"));

        descripciontxt.setColumns(20);
        descripciontxt.setRows(5);
        jScrollPane3.setViewportView(descripciontxt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS"));

        jLabel1.setText("ID:");

        tipocb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Familiar", "Matrimonial", "Suit", "Gran Suit" }));
        tipocb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tipocb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipocbActionPerformed(evt);
            }
        });

        jLabel6.setText("Nro de Habitación:");

        jLabel7.setText("Tipo de Habitación:");

        idtxt.setEditable(false);
        idtxt.setBackground(new java.awt.Color(255, 255, 255));
        idtxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });

        nrotxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        nrotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrotxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Piso:");

        pisotxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pisotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pisotxtMouseExited(evt);
            }
        });
        pisotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisotxtActionPerformed(evt);
            }
        });
        pisotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pisotxtKeyPressed(evt);
            }
        });

        jLabel3.setText("Estado:");

        estadocb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocupado", "Desocupado" }));
        estadocb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        estadocb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadocbActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio:");

        preciotxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        preciotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciotxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pisotxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipocb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadocb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pisotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipocb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadocb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        fond.setBackground(new java.awt.Color(255, 203, 101));
        fond.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 20, 30));

        fond1.setBackground(new java.awt.Color(255, 203, 101));
        fond1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.add(fond1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 20, 30));

        fond2.setBackground(new java.awt.Color(255, 203, 101));
        fond2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.add(fond2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 20, 30));

        btn_mHabitaciones7.setBackground(new java.awt.Color(204, 204, 204));
        btn_mHabitaciones7.setBorder(null);
        jPanel4.add(btn_mHabitaciones7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 310, 140));

        btn_mHabitaciones8.setBackground(new java.awt.Color(204, 204, 204));
        btn_mHabitaciones8.setBorder(null);
        jPanel4.add(btn_mHabitaciones8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 420, 340));

        btn_mHabitaciones9.setBackground(new java.awt.Color(204, 204, 204));
        btn_mHabitaciones9.setBorder(null);
        jPanel4.add(btn_mHabitaciones9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 260, 110));

        btn_mHabitaciones10.setBackground(new java.awt.Color(204, 204, 204));
        btn_mHabitaciones10.setBorder(null);
        jPanel4.add(btn_mHabitaciones10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 260, 150));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbtnActionPerformed
        editar();
        listar();
        nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_editarbtnActionPerformed

    private void buscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtnActionPerformed
        buscarEmpleado();
    }//GEN-LAST:event_buscarbtnActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila=tabla.getSelectedRow();
        if(fila==-1){}
        else{
            String estado=(String)tabla.getValueAt(fila,5);
            estadocb.setSelectedItem(estado);
            String tipo=(String)tabla.getValueAt(fila,3);
            tipocb.setSelectedItem(tipo);
            String nro=(String)tabla.getValueAt(fila,1);
            nrotxt.setText(nro);
            String id=(String)tabla.getValueAt(fila,0);
            idtxt.setText(id);
            ID=id;
            String piso=(String)tabla.getValueAt(fila,2);
            pisotxt.setText(piso);
            String precio=(String)tabla.getValueAt(fila,4);
            preciotxt.setText(precio);
            String descripcion=(String)tabla.getValueAt(fila,6);
            descripciontxt.setText(descripcion);
            String comodidades=(String)tabla.getValueAt(fila,7);
            comodidadestxt.setText(comodidades);

        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tipocbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipocbActionPerformed

    }//GEN-LAST:event_tipocbActionPerformed

    private void nrotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrotxtActionPerformed

    private void pisotxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pisotxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pisotxtMouseExited

    private void pisotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pisotxtActionPerformed

    private void pisotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pisotxtKeyPressed

    }//GEN-LAST:event_pisotxtKeyPressed

    private void estadocbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadocbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadocbActionPerformed

    private void preciotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciotxtActionPerformed

    private void nuevobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevobtnActionPerformed
    listar();
    nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevobtnActionPerformed

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mEmpleados().setVisible(true);
            }
        });
    }
    void listar(){
        String sql="select * from habitaciones";
        try {
            cn=dbConnection.connect();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]habitaciones=new Object[8];
            modelo=(DefaultTableModel)tabla.getModel();
            while(rs.next()){
                habitaciones[0]=rs.getString("habitacion_id");
                habitaciones[1]=rs.getInt("numero_habitacion");
                habitaciones[3]=rs.getString("tipo_habitacion");
                habitaciones[4]=rs.getDouble("precio_por_noche");
                habitaciones[5]=rs.getString("estado");
                habitaciones[2]=rs.getInt("piso");
                habitaciones[6]=rs.getString("descripcion");
                habitaciones[7]=rs.getString("comodidades");
                modelo.addRow(habitaciones);
                }
            tabla.setModel(modelo);
            } catch(Exception e){}
   
    }
    void limpiartabla(){
        for (int i=0;i<=tabla.getRowCount();i++){
            modelo.removeRow(i);
            i=i-1;
        }
    }
    void nuevo(){
        idtxt.setText("");
        nrotxt.setText("");
        preciotxt.setText("");
        pisotxt.setText("");
        descripciontxt.setText("");
        comodidadestxt.setText("");
    }
    void editar(){
        String precio=preciotxt.getText();
        String estado=estadocb.getSelectedItem().toString();
        String descripcion=descripciontxt.getText();
        String comodidades=comodidadestxt.getText();
        String nro=nrotxt.getText();
        String sql="update habitaciones set precio_por_noche='"+precio+"',estado='"+estado+"',descripcion='"+descripcion+"',comodidades='"+comodidades+"' where numero_habitacion="+nro;
        if(precio.equals("")){
            JOptionPane.showMessageDialog(null, "Se requiere ingresar datos ");
        }else{
            try{
                cn=dbConnection.connect();
                st=cn.createStatement();
                st.executeUpdate(sql);
                limpiartabla();
            }catch(Exception e){}
        }
    }
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mHabitaciones10;
    private javax.swing.JButton btn_mHabitaciones7;
    private javax.swing.JButton btn_mHabitaciones8;
    private javax.swing.JButton btn_mHabitaciones9;
    private javax.swing.JButton buscarbtn;
    private javax.swing.JTextArea comodidadestxt;
    private javax.swing.JTextArea descripciontxt;
    private javax.swing.JButton editarbtn;
    private javax.swing.JComboBox<String> estadocb;
    private javax.swing.JButton fond;
    private javax.swing.JButton fond1;
    private javax.swing.JButton fond2;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nrotxt;
    private javax.swing.JButton nuevobtn;
    private javax.swing.JTextField pisotxt;
    private javax.swing.JTextField preciotxt;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tipocb;
    // End of variables declaration//GEN-END:variables

    private void buscarEmpleado() {
        mBusqueda buscar = null;
        try {
            buscar = new mBusqueda(conn, "Empleados");
            buscar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(mUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
