/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

//import configuracion.Conexion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.dbConnection;

public class mHabitacionesAdmin extends javax.swing.JFrame {
    private Connection conn = null;
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int ID;
    public mHabitacionesAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
        conn = dbConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipocb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        nrotxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pisotxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        estadocb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        preciotxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripciontxt = new javax.swing.JTextArea();
        registrarbtn = new javax.swing.JToggleButton();
        editarbtn = new javax.swing.JButton();
        eliminarbtn = new javax.swing.JButton();
        buscarbtn = new javax.swing.JButton();
        nuevobtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_registrar1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nro", "Piso", "Tipo", "Precio", "Estado", "Descrip."
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);
        tabla.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 207, 501, 396));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 21, -1, -1));

        tipocb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Familiar", "Matrimonial", "Suite", "Gran Suite" }));
        tipocb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipocbActionPerformed(evt);
            }
        });
        jPanel1.add(tipocb, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 74, -1, -1));

        jLabel6.setText("Nro de Habitación:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 49, 196, -1));

        jLabel7.setText("Tipo de Habitación:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 77, 196, -1));

        idtxt.setEditable(false);
        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        jPanel1.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 18, -1, -1));

        nrotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrotxtActionPerformed(evt);
            }
        });
        jPanel1.add(nrotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 46, 97, -1));

        jLabel2.setText("Piso:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 21, -1, -1));

        pisotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pisotxtMouseExited(evt);
            }
        });
        pisotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisotxtActionPerformed(evt);
            }
        });
        pisotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pisotxtKeyPressed(evt);
            }
        });
        jPanel1.add(pisotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 18, 165, -1));

        jLabel3.setText("Estado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 105, -1, -1));

        estadocb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocupado", "Desocupado" }));
        estadocb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadocbActionPerformed(evt);
            }
        });
        jPanel1.add(estadocb, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 102, -1, -1));

        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 105, -1, -1));

        preciotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciotxtActionPerformed(evt);
            }
        });
        jPanel1.add(preciotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 102, 106, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 312, 189));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion:"));

        descripciontxt.setColumns(20);
        descripciontxt.setRows(5);
        jScrollPane3.setViewportView(descripciontxt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 207, 258, 396));

        registrarbtn.setText("REGISTRAR");
        registrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(registrarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, 30));

        editarbtn.setText("EDITAR");
        editarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(editarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 150, 30));

        eliminarbtn.setText("ELIMINAR");
        eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 150, 30));

        buscarbtn.setText("BUSCAR");
        buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(buscarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 150, 30));

        nuevobtn.setText("LIMPIAR");
        nuevobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevobtnActionPerformed(evt);
            }
        });
        getContentPane().add(nuevobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 150, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 6, -1, -1));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/devolver.png"))); // NOI18N
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_back.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        btn_registrar1.setBackground(new java.awt.Color(255, 204, 0));
        btn_registrar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_registrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_registrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 20, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipocbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipocbActionPerformed
     
    }//GEN-LAST:event_tipocbActionPerformed

    private void registrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarbtnActionPerformed
    registrar();
    }//GEN-LAST:event_registrarbtnActionPerformed

    private void eliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbtnActionPerformed
    eliminarHabitacion();
    nuevo();
    }//GEN-LAST:event_eliminarbtnActionPerformed

    private void editarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbtnActionPerformed
    editar();
    
// TODO add your handling code here:
    }//GEN-LAST:event_editarbtnActionPerformed

    private void buscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtnActionPerformed
    buscarHabitacion();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarbtnActionPerformed

    private void nrotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrotxtActionPerformed

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void pisotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pisotxtActionPerformed

    private void estadocbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadocbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadocbActionPerformed

    private void preciotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciotxtActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila=tabla.getSelectedRow();
        if(fila==-1){}
        else{
            String id=(String)tabla.getValueAt(fila,0);
            idtxt.setText(id);
            int nro=Integer.parseInt((String)tabla.getValueAt(fila,1).toString());
            nrotxt.setText(""+nro);
            int piso=Integer.parseInt((String)tabla.getValueAt(fila,2).toString());
            pisotxt.setText(""+piso);
            String tipo=(String)tabla.getValueAt(fila,3);
            tipocb.setSelectedItem(tipo);
            double precio=Double.parseDouble((String)tabla.getValueAt(fila,4).toString());
            preciotxt.setText(""+precio);
            String estado=(String)tabla.getValueAt(fila,5);
            estadocb.setSelectedItem(estado);
            String descripcion=(String)tabla.getValueAt(fila,6);
            descripciontxt.setText(descripcion);
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void nuevobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevobtnActionPerformed
        nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevobtnActionPerformed

    private void pisotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pisotxtKeyPressed


    }//GEN-LAST:event_pisotxtKeyPressed

    private void pisotxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pisotxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pisotxtMouseExited

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        retornarModulo();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mHabitacionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mHabitacionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mHabitacionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mHabitacionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mHabitacionesAdmin().setVisible(true);
            }
        });
    }
    
    void listar(){
        String sql="select * from Habitaciones";
        try {
            cn = dbConnection.connect();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]habitaciones=new Object[7];
            modelo=(DefaultTableModel)tabla.getModel();
            while(rs.next()){
                habitaciones[0]=rs.getString("habitacion_id");
                habitaciones[1]=rs.getInt("numero_habitacion");
                habitaciones[3]=rs.getString("tipo_habitacion");
                habitaciones[4]=rs.getDouble("precio_noche");
                habitaciones[5]=rs.getString("estado");
                habitaciones[2]=rs.getInt("piso");
                habitaciones[6]=rs.getString("descripcion");
                modelo.addRow(habitaciones);
                }
            tabla.setModel(modelo);
            } catch(Exception e){}
   
    }
    void registrar(){
        String nro=this.nrotxt.getText();
        String piso=this.pisotxt.getText();
        String precio=this.preciotxt.getText();
        String tipo=this.tipocb.getSelectedItem().toString();
        String estado=this.estadocb.getSelectedItem().toString();
        String t=null;
        if(tipo.equals("Normal")){
            t="N";
        }
        if(tipo.equals("Familiar")){
            t="F";
        }
        if(tipo.equals("Matrimonial")){
            t="M";
        }
        if(tipo.equals("Suite")){
            t="S";
        }
        if(tipo.equals("Gran Suite")){
            t="L";
        }
        String id="H"+nro+"P"+piso+t;
        String descripcion=descripciontxt.getText();
        if(nro.equals("")||piso.equals("")||precio.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar datos en las cajas.");
        }else{
            int contador_de_errores=0;
            for (int i=0;i<tabla.getRowCount();i++){
                int NRO=Integer.parseInt((String)tabla.getValueAt(i,1).toString());
                if(NRO==Integer.parseInt(nro)){
                    contador_de_errores=1;
                }
            }
            if(contador_de_errores==0){
                String sql="insert into Habitaciones(habitacion_id,numero_habitacion,piso,precio_noche,tipo_habitacion,estado,descripcion)values('"+id+"','"+nro+"','"+piso+"','"+precio+"','"+tipo+"','"+estado+"','"+descripcion+"')";
                try{
                    cn = dbConnection.connect();
                    st=cn.createStatement();
                    st.executeUpdate(sql);
                    limpiartabla();
                }catch(Exception e){}
                listar();
                nuevo();
            }else{
                JOptionPane.showMessageDialog(null, "El numero de habitacion que ingreso ya fue registrada en el sistema.");
            }
        }
    }
    void limpiartabla(){
        for (int i=0;i<=tabla.getRowCount();i++){
            modelo.removeRow(i);
            i=i-1;
        }
    }
    void editar(){
        int fila=tabla.getSelectedRow();
        String precio=preciotxt.getText();
        String piso=pisotxt.getText();
        String nro=nrotxt.getText();
        String estado=estadocb.getSelectedItem().toString();
        String descripcion=descripciontxt.getText();
        String tipo=tipocb.getSelectedItem().toString();
        String t=null;
        if(tipo.equals("Normal")){
            t="N";
        }
        if(tipo.equals("Familiar")){
            t="F";
        }
        if(tipo.equals("Matrimonial")){
            t="M";
        }
        if(tipo.equals("Suite")){
            t="S";
        }
        if(tipo.equals("Gran Suite")){
            t="L";
        }
        int NR=Integer.parseInt((String)tabla.getValueAt(fila,1).toString());
        String id="H"+nro+"P"+piso+t;
        if(nro.equals("")||piso.equals("")||precio.equals("")){
            JOptionPane.showMessageDialog(null, "Se requiere seleccionar una habitacion");
            }else{
                int contador_de_errores=0;
                for (int i=0;i<tabla.getRowCount();i++){
                    int NRO=Integer.parseInt((String)tabla.getValueAt(i,1).toString());
                    if(NRO==Integer.parseInt(nro)){
                        contador_de_errores=1;
                    }
                }
                if(NR==Integer.parseInt(nro)){
                    contador_de_errores=0;
                }                
                String sql="update Habitaciones set precio_noche='"+precio+"',estado='"+estado+"',descripcion='"+descripcion+"',piso='"+piso+"',habitacion_id='"+id+"',tipo_habitacion='"+tipo+"',numero_habitacion='"+nro+"' where numero_habitacion="+NR;
                if(contador_de_errores==0){
                    try{
                        cn = dbConnection.connect();
                        st=cn.createStatement();
                        st.executeUpdate(sql);
                        limpiartabla();
                    }catch(Exception e){}
                    listar();
                    nuevo();
                }else{
                    JOptionPane.showMessageDialog(null, "El numero de habitacion ya fue registrada para otra habitacion.");
                }
            }
        }
    
    void nuevo(){
        idtxt.setText("");
        nrotxt.setText("");
        preciotxt.setText("");
        pisotxt.setText("");
        descripciontxt.setText("");
    }
    
    void eliminarHabitacion() {
        int fila=tabla.getSelectedRow();
        if(fila==-1||nrotxt.equals("")){
            JOptionPane.showMessageDialog(null, "Se requiere seleccionar una habitacion");
        }else{
            int nro=Integer.parseInt((String)tabla.getValueAt(fila,1).toString());
            nrotxt.setText(""+nro);
            String sql="delete from Habitaciones where numero_habitacion="+nro;
            try{
                cn = dbConnection.connect();
                st=cn.createStatement();
                st.executeUpdate(sql);
                limpiartabla();
            }catch(Exception e){}
            listar();
            nuevo();
        }
    }
    
    private void eliminarID(String id) {
        PreparedStatement psmt = null;
        try {
            String sql = "DELETE FROM Habitaciones WHERE habitacion_id= ?";
            psmt = conn.prepareStatement(sql);
            psmt.setString(1, id);
            psmt.executeUpdate();
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
    }
    private void buscarHabitacion() {
            mBusqueda buscar = null;
            try {
                buscar = new mBusqueda(conn, "Habitaciones");
                buscar.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(mUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_registrar1;
    private javax.swing.JButton buscarbtn;
    private javax.swing.JTextArea descripciontxt;
    private javax.swing.JButton editarbtn;
    private javax.swing.JButton eliminarbtn;
    private javax.swing.JComboBox<String> estadocb;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nrotxt;
    private javax.swing.JButton nuevobtn;
    private javax.swing.JTextField pisotxt;
    private javax.swing.JTextField preciotxt;
    private javax.swing.JToggleButton registrarbtn;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tipocb;
    // End of variables declaration//GEN-END:variables

    private void retornarModulo() {
        this.dispose();
    }
   }

