/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author jtx
 */
public class mSelectorModulos extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public mSelectorModulos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_mPagos = new javax.swing.JButton();
        btn_mClientes = new javax.swing.JButton();
        btn_mClientes1 = new javax.swing.JButton();
        btn_mHabitaciones = new javax.swing.JButton();
        btn_mHabitaciones1 = new javax.swing.JButton();
        btn_mReservas1 = new javax.swing.JButton();
        btn_mReservas = new javax.swing.JButton();
        btn_mUsuarios1 = new javax.swing.JButton();
        btn_mUsuarios = new javax.swing.JButton();
        btn_mEmpleados = new javax.swing.JButton();
        btn_mEmpleados1 = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_mPagos1 = new javax.swing.JButton();
        btn_mHabitaciones2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        letras17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(774, 512));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mPagos.setFont(btn_mPagos.getFont().deriveFont((btn_mPagos.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mPagos.getFont().getSize()+3));
        btn_mPagos.setText("Pagos");
        btn_mPagos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(btn_mPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 140, 30));

        btn_mClientes.setFont(btn_mClientes.getFont().deriveFont((btn_mClientes.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mClientes.getFont().getSize()+3));
        btn_mClientes.setText("Clientes");
        btn_mClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_mClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 140, 30));

        btn_mClientes1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mClientes1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(btn_mClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 20, 30));

        btn_mHabitaciones.setFont(btn_mHabitaciones.getFont().deriveFont((btn_mHabitaciones.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mHabitaciones.getFont().getSize()+3));
        btn_mHabitaciones.setText("Habitaciones");
        btn_mHabitaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_mHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mHabitacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 140, 30));

        btn_mHabitaciones1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mHabitaciones1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(btn_mHabitaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 20, 30));

        btn_mReservas1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mReservas1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(btn_mReservas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 20, 30));

        btn_mReservas.setFont(btn_mReservas.getFont().deriveFont((btn_mReservas.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mReservas.getFont().getSize()+3));
        btn_mReservas.setText("Reservas");
        btn_mReservas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_mReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mReservasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 140, 30));

        btn_mUsuarios1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mUsuarios1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(btn_mUsuarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 20, 30));

        btn_mUsuarios.setFont(btn_mUsuarios.getFont().deriveFont((btn_mUsuarios.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mUsuarios.getFont().getSize()+3));
        btn_mUsuarios.setText("Usuarios");
        btn_mUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_mUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 140, 30));

        btn_mEmpleados.setFont(btn_mEmpleados.getFont().deriveFont((btn_mEmpleados.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_mEmpleados.getFont().getSize()+3));
        btn_mEmpleados.setText("Empleados");
        btn_mEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_mEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 140, 30));

        btn_mEmpleados1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mEmpleados1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(btn_mEmpleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 20, 30));

        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_back.setText("<  ");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 57, 30));

        btn_mPagos1.setBackground(new java.awt.Color(255, 204, 0));
        btn_mPagos1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(btn_mPagos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 20, 30));

        btn_mHabitaciones2.setBackground(new java.awt.Color(255, 204, 0));
        btn_mHabitaciones2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(btn_mHabitaciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 20, 30));

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 540, 280));

        letras17.setFont(letras17.getFont().deriveFont(letras17.getFont().getStyle() | java.awt.Font.BOLD, 23));
        letras17.setText("Selector de Modulos");
        jPanel1.add(letras17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 270, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.abrirLogin();
        //ELIMINAR
        super.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_mHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mHabitacionesActionPerformed
        abrirHabitaciones();
    }//GEN-LAST:event_btn_mHabitacionesActionPerformed

    private void btn_mClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mClientesActionPerformed
        abrirClientes();
    }//GEN-LAST:event_btn_mClientesActionPerformed

    private void btn_mEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mEmpleadosActionPerformed
        abrirEmpleados();
    }//GEN-LAST:event_btn_mEmpleadosActionPerformed

    private void btn_mUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mUsuariosActionPerformed
        abrirUsuarios();
    }//GEN-LAST:event_btn_mUsuariosActionPerformed

    private void btn_mReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mReservasActionPerformed
        abrirReservas();
    }//GEN-LAST:event_btn_mReservasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_mClientes;
    private javax.swing.JButton btn_mClientes1;
    private javax.swing.JButton btn_mEmpleados;
    private javax.swing.JButton btn_mEmpleados1;
    private javax.swing.JButton btn_mHabitaciones;
    private javax.swing.JButton btn_mHabitaciones1;
    private javax.swing.JButton btn_mHabitaciones2;
    private javax.swing.JButton btn_mPagos;
    private javax.swing.JButton btn_mPagos1;
    private javax.swing.JButton btn_mReservas;
    private javax.swing.JButton btn_mReservas1;
    private javax.swing.JButton btn_mUsuarios;
    private javax.swing.JButton btn_mUsuarios1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel letras17;
    // End of variables declaration//GEN-END:variables
    public void desabilitarModulos() {
        this.btn_mUsuarios.setEnabled(false);
        this.btn_mUsuarios1.setEnabled(false);
        this.btn_mEmpleados.setEnabled(false);
        this.btn_mEmpleados1.setEnabled(false);
    }
    
    public void abrirLogin(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            //UIManager.put( "Button.arc", 999 );
            //UIManager.put( "Component.arc", 999 );
            //UIManager.put( "ProgressBar.arc", 999 );
            //UIManager.put( "TextComponent.arc", 999 );
            UIManager.put("Button.arc", 2); // Radio de las esquinas redondeadas
            UIManager.put("Button.borderColor", Color.BLACK); // Color del borde
            UIManager.put("Button.focusedBorderColor", Color.BLACK); // Color del borde cuando está enfocado
            UIManager.put("Button.default.borderColor", Color.BLACK); // Color del borde para el botón por defecto
            UIManager.put("Component.borderWidth", 2);

            //UIManager.put("Button.border", new LineBorder(Color.BLACK,2));
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mLogin().setVisible(true);
            }
            
        });
    }

    private void abrirHabitaciones() {
        mHabitaciones modulo = new mHabitaciones();
        modulo.setVisible(true);
        this.setVisible(false);
    }

    private void abrirClientes() {
        mClientes modulo = new mClientes();
        modulo.setVisible(true);
        this.setVisible(false);
    }

    private void abrirEmpleados() {
        mEmpleados modulo = new mEmpleados();
        modulo.setVisible(true);
        this.setVisible(false);
    }
    
    private void abrirUsuarios() {
        mUsuarios modulo = new mUsuarios();
        modulo.setVisible(true);
        this.setVisible(false);
    }
    
    private void abrirReservas() {
        mReservas modulo = new mReservas();
        modulo.setVisible(true);
        this.setVisible(false);
    } 
    
}
