/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sql.dbConnection;

/**
 *
 * @author jtx
 */
public class mUsuarios extends javax.swing.JFrame {

    //private DefaultTableModel tableModel;

    public class Usuario {

        private int id;
        private String nombre;
        private String contrasena;
        private boolean rol;
        private String creadoEn;
        private String actualizadoEn;

        public Usuario(int id, String nombre, String contrasena, boolean rol, String creadoEn, String actualizadoEn) {
            this.id = id;
            this.nombre = nombre;
            this.contrasena = contrasena;
            this.rol = rol;
            this.creadoEn = creadoEn;
            this.actualizadoEn = actualizadoEn;
        }

        // Getters y setters...
        public int getId() {
            return id;
        }

        public String getNombre() {
            return nombre;
        }

        public String getContrasena() {
            return contrasena;
        }

        public boolean isRol() {
            return rol;
        }

        public String getCreadoEn() {
            return creadoEn;
        }

        public String getActualizadoEn() {
            return actualizadoEn;
        }
    }

    private Connection conn = null;

    /**
     * Creates new form mUsuarios
     */
    public mUsuarios() {
        initComponents();
        conn = dbConnection.connect();
        rellenarTabla();
    }

    /**
     * Creates new form mUsuarios2
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_eliminar1 = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar1 = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_buscar1 = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        letras17 = new javax.swing.JLabel();
        btn_registrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_usuarios.setAutoCreateRowSorter(true);
        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Contraseña", "rol", "Creación", "Actualización"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_usuarios.setColumnSelectionAllowed(true);
        tbl_usuarios.setFillsViewportHeight(true);
        tbl_usuarios.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_usuarios.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(tbl_usuarios);
        tbl_usuarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tbl_usuarios.getColumnModel().getColumnCount() > 0) {
            tbl_usuarios.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 48, 526, 197));

        btn_back.setText("<");
        btn_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_back.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_eliminar1.setBackground(new java.awt.Color(255, 204, 0));
        btn_eliminar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_eliminar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btn_eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 20, 30));

        btn_eliminar.setFont(btn_eliminar.getFont().deriveFont((btn_eliminar.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_eliminar.getFont().getSize()+3));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 110, 30));

        btn_modificar1.setBackground(new java.awt.Color(255, 204, 0));
        btn_modificar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_modificar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btn_modificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 30));

        btn_modificar.setFont(btn_modificar.getFont().deriveFont((btn_modificar.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_modificar.getFont().getSize()+3));
        btn_modificar.setText("Añadir / Modificar");
        btn_modificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        btn_buscar1.setBackground(new java.awt.Color(255, 204, 0));
        btn_buscar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_buscar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_buscar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btn_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 20, 30));

        btn_buscar.setFont(btn_buscar.getFont().deriveFont((btn_buscar.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, btn_buscar.getFont().getSize()+3));
        btn_buscar.setText("Buscar");
        btn_buscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 282, 526, -1));

        letras17.setFont(letras17.getFont().deriveFont(letras17.getFont().getStyle() | java.awt.Font.BOLD, 26));
        letras17.setText("Usuarios");
        getContentPane().add(letras17, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 6, -1, -1));

        btn_registrar1.setBackground(new java.awt.Color(255, 204, 0));
        btn_registrar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_registrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_registrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btn_registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        eliminarUsuario();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        buscarUsuario();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            UIManager.put("Button.arc", 5); // Radio de las esquinas redondeadas
            UIManager.put("Button.borderColor", Color.BLACK); // Color del borde
            UIManager.put("Button.focusedBorderColor", Color.BLACK); // Color del borde cuando está enfocado
            UIManager.put("Button.default.borderColor", Color.BLACK); // Color del borde para el botón por defecto
            UIManager.put("Component.borderWidth", 2); // Grosor del borde
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mUsuarios().setVisible(true);
        });
    }

    public List<mUsuarios.Usuario> obtenerUsuarios() {
        List<mUsuarios.Usuario> usuarios = new ArrayList<>();
        String query = "SELECT * FROM Usuarios";

        try (
                Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

            while (rs.next()) {
                int id = rs.getInt("usuario_id");
                String nombre = rs.getString("nombre_usuario");
                String contrasena = rs.getString("contrasena");
                boolean rol = rs.getBoolean("admin");
                String creadoEn = rs.getString("creado_en");
                String actualizadoEn = rs.getString("actualizado_en");
                mUsuarios.Usuario nuevo_usuario = new mUsuarios.Usuario(id, nombre, contrasena, rol, creadoEn, actualizadoEn);
                usuarios.add(nuevo_usuario);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return usuarios;
    }

    public void rellenarTabla() {
        DefaultTableModel tableModel = (DefaultTableModel) this.tbl_usuarios.getModel();
        tableModel.setRowCount(0);
        List<mUsuarios.Usuario> usuarios = obtenerUsuarios();
        for (mUsuarios.Usuario usuario : usuarios) {
            tableModel.addRow(new Object[]{
                usuario.getId(),
                usuario.getNombre(),
                usuario.getContrasena(),
                usuario.isRol(),
                usuario.getCreadoEn(),
                usuario.getActualizadoEn()
            });
        }
    }

    //Registrar usuarios
    /*
    private void registrarUsuario() {
        JOptionPane.showInputDialog("")
    }*/
    private void buscarUsuario() {
        mBusqueda buscar = null;
        try {
            buscar = new mBusqueda(conn, "Usuarios");
            buscar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(mUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*
    private void actualizarUsuario() {
        JOptionPane.showInputDialog("")
    }
     */
    private void eliminarUsuario() {
        String id = (JOptionPane.showInputDialog("Ingrese id de usuario"));
        eliminarID(id);
        //this.tbl_usuarios.removeAll();
        rellenarTabla();
    }

    //BASE DE DATOS
    private void eliminarID(String id) {
        PreparedStatement psmt = null;
        try {
            String sql = "DELETE FROM Usuarios WHERE usuario_id = ?";
            psmt = conn.prepareStatement(sql);
            psmt.setString(1, id);
            psmt.executeUpdate();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_eliminar1;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_modificar1;
    private javax.swing.JButton btn_registrar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel letras17;
    private javax.swing.JTable tbl_usuarios;
    // End of variables declaration//GEN-END:variables
}
